language: node_js
node_js: node
deploy:
provider: heroku
api_key:
secure: m/UpoXfZEJ/xHeADIVncTzzHZSDcrz+VK6RWAo3nvA4MJdvCx69YcFK/Bhb21tBYsG9l1WG5EwX0KCBcH7uKKHwNuDCLECBX8Xf4BLb2qA6u7/ImSUTQt91UBsqLkhPdbcsyS/T9Kpd6fBM4n1hkA3L+Af++Q1ptFiI7YaNThFVwYmFDMMbD5iplEqaCM85gQmYpY+h40FX2vTI2nEPZVah4VRVMxlypkwhPF+Tnd1WanpXB3rfjur5+VKwToOFOwKZZpPApWLPi3Ewko7H06qchI6ut/2/GGCj+rarWTaK6ntAcYU6jGCyo1aWU/eJzd5nkBwR+sLJJClXuq7XBYvApq/LdtVIkedLuEXrpUYYC4MFyA6x5dfKqMJZJ71eN5ZXyOS3rLjY9wxea6of3Req01up4eh/uxyY7iWTPa66R0Nx5D0MeCAng+FCybTBfEVlBsVvLqpKMYhEdTtLqdWoUZm3ev1KR418HQ25S6OqLQBYdbK66krUFmjftSkPZr7m3kIHD3F+WEYfXJlWo6DRdipy6O/ZeT3hQVNq6TMScDf3+3EzudyTWTpPPntHoXXjdarhbOeo9tnAy4h5U815fmItB2X72yVQaVsD/5DmieauMcvKB0j5/sj4gMWbNG+oni8iDa8squkYhCbdbgwAmAF3I3VV6hI3C01k+UX8=
app: music-node-app
  on:
    repo: jorgerodriguez434/music-node-app
