language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: m1qwZDCrfE67FRnExBhTON0x4kNrTpNm8tz+KhqHEjKLhC2+YffSoCRd3jvxtjCSFNUmFBljuBmkHfkXKYCioWtCvHKvJ/zYvTptS0kRBtFA6kOqGrGU88Vi7RYT56QLsLB4naaU4SbOQLCV/hyhn0Qm1Kn4HHNepXBdtSGXlQPnmifKyB73PXcfk1iDxIQg/hSSAmbT0m00n+p128Sv0nvS3ZCILiQotUOU9l1OTeDPJpsF3rCVwkvF7Gksir+hQTSk0vEMmt47OxMkdaecybX4dGNsJfawjZ99V5S0ElU4Eh1551wn+08jbzWlEOH+ywkrWwwOosuK7Fq9nyrIwYrgk6injKDDTaH/MYQQ9cJBehW2xsoTyHVQNh9V3OlCcum1CeUM0PZh9J3fVn2K4EHoKLdbWk0EQrHGX+lSM0l+UwRTUrSjOpPmru+7nwBKQ3g+jOuTxrF0q+n0J3FtXCWslTU5eIEFhl9hWMRAEc7Oo2qkO+Smtr2/bH3e/N67YTO5aBTtq1IkKQNS1K4wTJ/CI5B1cvNboOQRZusvX+svoX69ktSamE8+pT6kypSv0kaYZljLNQs2Y+lhOgdahnzLvxDINtHv5bIND3YU6BSvRiykTU1Z/d+tONpA/ztc5rLfeTV9hksNTM70HfDKR6DegRS3iQFDbPicUjm1tz0=
  app: cherry-cupcake-67556
  on:
    repo: jorgerodriguez434/music-node-app
