language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: CQgnj9KzDsgx4oN/2nfQFSktmkBHms56oo4CaYU9MwAuhXGWzT7/BaVZAOfoMII3b2CWyUetYhk1GYipEM+xillqBMvKBmNBEpoJa9cDzL4MiZlccMX4Fls6pai5juw98X2V3bB4hMsOcdIlGudbuErr5iJmbAtt1Nya8SBl22YADKlQGLdNI3/jcQ9vU5bubhLk7JxLKZ1/ajgfYNZbf1CEO6f20V7cx99NMTGRIFQMfrCyF7g348lJUrW8CxVv0wn7Xm/rhPVqmItwufg1Dj2bbVRciuHQEAOQkw2HNkb84qSGAxw6Q+j7tw9zmkELKPzOtiWJc4fEnPh9dWtyFUeFvMx45eU4TqQMfzJo2WIJtpt+36J6pDbj/fwWlPAOKDyi7eR/gVM59XgL7MUtrjsRnHO+xEqwm7YXi+PRiFWuxBCLJ60jCglyFlUuLxWJbwvZ/HLJyMEpidEQT8mnhkdKaGQf3h44C0BLgVEMoIFb9b1tLbkSPAEaPRfs1Q1zenDLATamFqdalK6uBpXXiKaqUZDQUCBh8LwkpT8vjQR2P+6APwJD+L8fUN/TwrNYGjD4vrTpqk+EaPWwBuqk2PynMrlPTW58V4/sm+yMTXZdcP410mPxdxTPYHlVrfB3c7QlkNJjEqe8anht4Dge2bc7b/Vjqg5C8TD2LE6929o=
  app: lychee-shortcake-58019
  on:
    repo: jorgerodriguez434/music-node-app
